-- Tabla para blacklist de match IDs de la API
-- Permite ocultar partidos específicos sin eliminarlos de la API

CREATE TABLE IF NOT EXISTS match_blacklist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reason TEXT
);

-- Índice para búsquedas rápidas por match_id
CREATE INDEX IF NOT EXISTS idx_match_blacklist_match_id ON match_blacklist(match_id);

-- Comentario sobre la tabla
COMMENT ON TABLE match_blacklist IS 'Almacena IDs de partidos que deben ser ocultados de la vista pública';
